"""baseline: alpha-generation core schema

Single squashed baseline. The six migrations this replaces built the original
36-table schema and then tore 20 of those tables back down; a fresh clone would
have created and dropped them for nothing. Squashed after the pruned schema was
verified against the models (``alembic check`` clean) and the live database was
stamped at this revision.

The 15 tables here are the alpha-generation core described in STRATEGY.md.
Note ``brain_fetch_log`` carries CHECK(http_method = 'GET'): the catalog fetcher
is genuinely read-only. Simulation is a separate path — see docs/DECISIONS.md.

Revision ID: f0be3fc3cdad
Revises: 
Create Date: 2026-08-04 01:48:36.533317
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # used by JSONB(astext_type=Text()) variant renders
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0be3fc3cdad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphas',
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('normalized_expression', sa.Text(), nullable=True),
    sa.Column('expression_hash', sa.String(length=64), nullable=False),
    sa.Column('family_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('universe', sa.String(length=32), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('neutralization', sa.String(length=32), nullable=True),
    sa.Column('decay', sa.Integer(), nullable=True),
    sa.Column('truncation', sa.Float(), nullable=True),
    sa.Column('settings_extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('validation_warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('feature_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('mutation_type', sa.String(length=32), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mutation_type IN ('operator_swap', 'parameter_tune', 'field_substitution', 'neutralization_decay', 'composition')", name=op.f('ck_alphas_mutation_type_valid')),
    sa.CheckConstraint("status IN ('untested', 'testing', 'passed', 'rejected', 'improved', 'archived')", name=op.f('ck_alphas_status_valid')),
    sa.ForeignKeyConstraint(['parent_id'], ['alphas.id'], name=op.f('fk_alphas_parent_id_alphas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alphas')),
    sa.UniqueConstraint('expression_hash', name='alpha_expression_hash')
    )
    with op.batch_alter_table('alphas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alphas_family_key'), ['family_key'], unique=False)

    op.create_table('brain_fetch_log',
    sa.Column('http_method', sa.String(length=8), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('num_records', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("http_method = 'GET'", name=op.f('ck_brain_fetch_log_read_only_get')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brain_fetch_log'))
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('datasets',
    sa.Column('dataset_code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('universe', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('field_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('dataset_code', 'region', 'delay', 'universe', name='dataset_config')
    )
    op.create_table('llm_runs',
    sa.Column('prompt_key', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'error', 'cached')", name=op.f('ck_llm_runs_status_valid')),
    sa.CheckConstraint("tier IN ('opus', 'sonnet', 'haiku', 'reserve')", name=op.f('ck_llm_runs_tier_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_runs'))
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_runs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_task'), ['task'], unique=False)

    op.create_table('operators',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('returns', sa.String(length=16), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('typical_usage', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('arithmetic', 'time_series', 'cross_section', 'group', 'logical', 'transformational', 'vector', 'special')", name=op.f('ck_operators_category_valid')),
    sa.CheckConstraint("returns IN ('matrix', 'vector', 'group', 'boolean')", name=op.f('ck_operators_returns_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operators')),
    sa.UniqueConstraint('name', name=op.f('uq_operators_name'))
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('alpha_status_history',
    sa.Column('alpha_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("from_status IN ('untested', 'testing', 'passed', 'rejected', 'improved', 'archived')", name=op.f('ck_alpha_status_history_from_status_valid')),
    sa.CheckConstraint("to_status IN ('untested', 'testing', 'passed', 'rejected', 'improved', 'archived')", name=op.f('ck_alpha_status_history_to_status_valid')),
    sa.ForeignKeyConstraint(['alpha_id'], ['alphas.id'], name=op.f('fk_alpha_status_history_alpha_id_alphas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alpha_status_history'))
    )
    op.create_table('data_fields',
    sa.Column('field_code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('alpha_count', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('universe', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('price', 'volume', 'fundamentals', 'cashflow', 'news', 'macro', 'analyst', 'corporate', 'alternative', 'options', 'risk')", name=op.f('ck_data_fields_category_valid')),
    sa.CheckConstraint("field_type IN ('MATRIX', 'VECTOR', 'GROUP')", name=op.f('ck_data_fields_field_type_valid')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_data_fields_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_fields')),
    sa.UniqueConstraint('field_code', 'region', 'delay', 'universe', name='field_config')
    )
    with op.batch_alter_table('data_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_fields_field_code'), ['field_code'], unique=False)

    op.create_table('operator_arguments',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('arg_type', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_window', sa.Boolean(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("arg_type IN ('matrix', 'vector', 'group', 'int', 'float', 'boolean', 'const')", name=op.f('ck_operator_arguments_arg_type_valid')),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_operator_arguments_operator_id_operators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_arguments')),
    sa.UniqueConstraint('operator_id', 'position', name='operator_arg_position')
    )
    op.create_table('operator_compatibility',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('other_operator_name', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_operator_compatibility_operator_id_operators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_compatibility')),
    sa.UniqueConstraint('operator_id', 'other_operator_name', 'relation', name='operator_compat_edge')
    )
    op.create_table('operator_examples',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('expr', sa.Text(), nullable=False),
    sa.Column('is_good', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_operator_examples_operator_id_operators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_examples'))
    )
    op.create_table('simulation_imports',
    sa.Column('alpha_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('paste', 'csv', 'json', 'brain_api')", name=op.f('ck_simulation_imports_source_valid')),
    sa.ForeignKeyConstraint(['alpha_id'], ['alphas.id'], name=op.f('fk_simulation_imports_alpha_id_alphas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_imports'))
    )
    with op.batch_alter_table('simulation_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_imports_alpha_id'), ['alpha_id'], unique=False)

    op.create_table('alpha_metrics',
    sa.Column('simulation_import_id', sa.Integer(), nullable=False),
    sa.Column('alpha_id', sa.Integer(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('fitness', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('margin_bps', sa.Float(), nullable=True),
    sa.Column('subuniverse_sharpe', sa.Float(), nullable=True),
    sa.Column('self_correlation', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('long_count', sa.Integer(), nullable=True),
    sa.Column('short_count', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('passed_all_checks', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alpha_id'], ['alphas.id'], name=op.f('fk_alpha_metrics_alpha_id_alphas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_import_id'], ['simulation_imports.id'], name=op.f('fk_alpha_metrics_simulation_import_id_simulation_imports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alpha_metrics')),
    sa.UniqueConstraint('simulation_import_id', name=op.f('uq_alpha_metrics_simulation_import_id'))
    )
    with op.batch_alter_table('alpha_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alpha_metrics_alpha_id'), ['alpha_id'], unique=False)

    op.create_table('field_tags',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['data_fields.id'], name=op.f('fk_field_tags_field_id_data_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_field_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id', 'tag_id', name=op.f('pk_field_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_tags')
    with op.batch_alter_table('alpha_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alpha_metrics_alpha_id'))

    op.drop_table('alpha_metrics')
    with op.batch_alter_table('simulation_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_imports_alpha_id'))

    op.drop_table('simulation_imports')
    op.drop_table('operator_examples')
    op.drop_table('operator_compatibility')
    op.drop_table('operator_arguments')
    with op.batch_alter_table('data_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_fields_field_code'))

    op.drop_table('data_fields')
    op.drop_table('alpha_status_history')
    op.drop_table('tags')
    op.drop_table('operators')
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_runs_task'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_module'))

    op.drop_table('llm_runs')
    op.drop_table('datasets')
    op.drop_table('categories')
    op.drop_table('brain_fetch_log')
    with op.batch_alter_table('alphas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alphas_family_key'))

    op.drop_table('alphas')
    # ### end Alembic commands ###
